apiVersion: apps/v1
kind: Deployment
metadata:
  name:  commands-depl
  namespace: default
  labels:
    app:  commands-depl
spec:
  selector:
    matchLabels:
      app: commandsservice
  replicas: 1
  template:
    metadata:
      labels:
        app: commandsservice
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  commandsservice
        image:  paraylls/commandsservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandsservice
  ports:
  - name: commandsservice
    protocol: TCP
    port: 80
    targetPort: 80
